### ISSUE TITLE
skip this update no longer working

### ISSUE THREAD

**Issue by BillH99999** [AdliceSoftware/UCheck#12]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I used the Action Skip this Update for the Google Chrome update to 119.0.6045.202 which isn't currently being offered to me by Google.
The update was removed from the list.
I did another scan.
The update again listed even though the exclusion was still listed in the settings.

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [ ] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by BillH99999** [comment]
![image1](https://github.com/AdliceSoftware/UCheck/assets/26846819/cb0dcfd4-97d6-4a6a-acce-4a26f8972551)

![image2](https://github.com/AdliceSoftware/UCheck/assets/26846819/69447c73-7833-4a63-ad67-623ddcc64434)

**Comment by stevehoek** [comment]
I'm seeing the same thing in latest release

**Comment by stevehoek** [comment]
It is working again in the latest BETA 5.0.7 but it seems to capture the latest version of the app for the Version column instead of the older version that I want to ignore

For example, an app called BD_Rebuilder (portable) ships with alot of video processing tools in its subfolders, such as MKVtoolnix.  I have the latest MKVtoolnix (portable) installed in a different location but UCheck flags the older version installed with BD_Rebuilder.  When I "skip this update" on the older versions, it shows in the Settings | Exclusions the newer version that it was expecting.  

I think Exclusions should show the path of the app that was excluded, as well as the (older/newer) version that was excluded

**Comment by Tigzy** [comment]
It is fixed already, but not yet in a version. It will be in the next BETA.

**Comment by stevehoek** [comment]
> It is fixed already, but not yet in a version. It will be in the next BETA.

That's great!  Will you please consider showing more information in the Exclusion page?  Like path, excluded version, latest version

**Comment by BillH99999** [comment]
> It is fixed already, but not yet in a version. It will be in the next BETA.

Thanks @Tigzy 

Bill

**Comment by BillH99999** [comment]
I just noticed this.  I don't know if it is related.

I used "skip this update" on Ultimate Windows Tweaker.  I have not selected "Excluded" in Display, yet Ultimate Windows Tweaker is showing in the list.

![image1](https://github.com/AdliceSoftware/UCheck/assets/26846819/107032ae-249d-4258-a16f-9381de85b2e8)

Bill

**Comment by Tigzy** [comment]
Should be fixed with 5.1
