### ISSUE TITLE
Make it possible to change search engine

### ISSUE THREAD

**Issue by Shoopzar** [AdliceSoftware/UCheck#38]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I checked that the feature I'm requesting is not available in UCheck Beta
- [X] I checked that the feature I'm requesting was not already requested

### Which feature do you want to be added ?

I want a way to change search engine when searching for the tool. As example duckduckgo instead of google search engine.

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
For that you just need to go to EDGE and change the default search engine: 
https://www.process.st/how-to/change-search-engine-on-microsoft-edge/#:~:text=Open%20Microsoft%20Edge%20and%20click,engine%20(e.g.%2C%20Google).

Why EDGE ? Because it's only web browser we know is installed on the machine, and is well integrated into the system. 
Also it's easy to read from the registry, and can easily be changed by the user.
